services:
  # Web Service
  - type: web
    name: melascan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn melascan.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: melascan.settings_prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOST
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: melascan-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.0

  # Database
  - type: pserv
    name: melascan-db
    plan: free
    env: postgres